from pybricks.tools import wait
from pybricks.parameters import Stop
import Drive, Arm, Missions

def acrossL():
    Drive.curve(200, -90)
    wait(100)
    Drive.straight(1200)
    Drive.curve(200, -65)

def acrossR():
    Drive.curve(200, 90)
    wait(100)
    Drive.straight(1200)
    Drive.curve(200, 65)

def MovementA():
    Drive.straight(20)
    Drive.turn(-90)
    Arm.armUp()
    Drive.straight(325)
    Drive.turn(-30)
    Arm.resetArm()
    Drive.turn(75)
    Arm.armUp()
    Drive.turn(-45)
    Drive.straight(200)
    Drive.turn(-45)
    Drive.back(400)
    Drive.turn(-45)
    Drive.back(300)
    Drive.turn(65)
    Drive.back(200)
    Drive.straight(100)
    Drive.turn(-70)
    Drive.back(150)
    Drive.back_square()
    Drive.straight(250)
    Drive.turn(90)
    Drive.straight(810)
    Drive.turn(90)
    Arm.resetArm()
    Arm.turnArm(20, 20)
    Drive.straight(140)
    Arm.resetArm()
    Arm.armUp()
    Drive.straight(-125)
    Drive.turn(90)
    Drive.back(500)
    Drive.turn(-90)
    Drive.back(500)
    Drive.turn(45)
    Drive.back(400)

def MovementB():
    Drive.turn(20)
    Drive.straight(575)
    Arm.hook()
    Drive.turn(250) #To knock over that one thing
    Missions.mission1()
    Drive.turn(45)
    Drive.straight(150)
    Missions.mission2()
    Arm.armUp()
    Drive.turn(55)
    Drive.straight(200, then=Stop.COAST)
    Drive.front_square()
    Missions.mission3()
    Drive.back_square()
    Drive.straight(250)
    Drive.turn(-90)
    Drive.straight(540)
    Drive.turn(-45)
    Arm.resetArm()
    Drive.straight(200)
    Missions.mission10()
    Drive.back(250)
    Drive.turn(90)
    Missions.mission5()
    Drive.straight(875)
    Drive.turn(45)
    Missions.mission13()
    Drive.back(325, speed=200)
    Drive.turn(90)
    Drive.back(200, speed=775)
    Drive.straight(500)

def MovementC():
    Drive.straight(25)
    Drive.turn(90)
    Arm.turnArm(25, 90)
    Drive.straight(300)
    Drive.straight(400, speed=250)
    Drive.turn(25)
    Drive.turn(-25)
    Drive.back(300)
    Drive.turn(-90)
    Missions.mission6()
    Drive.back(200)
    Arm.armUp()
    Drive.turn(45)
    Drive.back(200)
    Drive.back_square()
    Drive.turn(90)
    Missions.mission15()
    Drive.straight(200)
    Drive.turn(45)
    Drive.straight(200)
    Drive.turn(45)
    Drive.straight(200)
    Missions.mission8()
    Drive.back(500)
    Drive.turn(-45)
    Drive.back(200)

def MovementD():
    Arm.armUp()
    Drive.turn(-22.5)
    Drive.straight(400)
    Drive.turn(-22.5)
    Drive.straight(500)
    Drive.turn(90)
    Drive.back(25)
    Arm.resetArm()
    Drive.turn(-45, speed=25)
